export const serviceProviders = [
  {
    name: 'Mark',
     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
     coordinate: [ 40.764466, -73.974488 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
    pincolor: 'green',
  },
  {
    name: 'Frank',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.764656, -73.980907 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Leslie',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.764838, -73.981193 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Kevin',
     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
   coordinate: [ 40.748418, -73.985702 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Don',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.762389, -73.973817 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Jane',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.779707, -73.979012 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Bob',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.747067, -74.004496 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Jennifer',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.765298, -73.976022 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Ivan',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.791939, -73.963466 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Taq',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.792364, -73.964200 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Rich',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.791646, -73.964681 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Lisa',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.764298, -73.971752 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'John',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.764116, -73.973581 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Fiona',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.763241, -73.975782 ],
    electrician: true,
    plumber: false,
    license: 'NYXXXX33',
     pincolor: 'green',
  },
  {
    name: 'Poppy',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.758702, -73.978598 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
     pincolor: 'red',
  },
  {
    name: 'Katie',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.758889, -73.985125 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Maria',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.771156, -73.979802 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Shirley',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.761432, -73.977645 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Harry',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.792084, -73.966925 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Tim',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.764859, -73.975421 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Duncan',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.763560, -73.972198 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Marv',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
    coordinate: [ 40.791871, -73.966812 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
  {
    name: 'Holly',
     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbxZsZYZth9Zxyc0H9hdcL4uuophCsnrRopbzO0zv35TqKjRtV',
   coordinate: [ 40.765126, -73.979924 ],
    electrician: false,
    plumber: true,
    license: 'NYXXXX33',
    pincolor: 'red',
  },
];